// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UserProfiler.Models;

namespace UserProfiler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180124121216_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("UserProfiler.Models.AnonymousUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppVersion")
                        .IsRequired();

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("UserAgent")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AnonymousUsers");
                });

            modelBuilder.Entity("UserProfiler.Models.ContentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("UserProfiler.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AnonymousUserId");

                    b.Property<int>("ContentPageId");

                    b.Property<string>("Coordinates");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<string>("Kind")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AnonymousUserId");

                    b.HasIndex("ContentPageId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("UserProfiler.Models.UserActivity", b =>
                {
                    b.HasOne("UserProfiler.Models.AnonymousUser")
                        .WithMany("ActivityHistory")
                        .HasForeignKey("AnonymousUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UserProfiler.Models.ContentPage", "ContentPage")
                        .WithMany("ActivityHistory")
                        .HasForeignKey("ContentPageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
